name: XaynFrontOfficeSdk
targets:
  XaynFrontOfficeSdk:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [XaynFrontOfficeSdk]
    info:
      path: ./Info.plist
      version: 1.0.23
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
