//
// InputUserWithHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InputUserWithHistory: Codable, JSONEncodable, Hashable {

    /** The history is an sequence of entries representing documents visited by the user.  It is ordered from the  \"oldest\" interaction at index 0 to the \"newest\" interaction at the highest index.  History entries do not need to have a timestamp, if no timestamp is given it is approximated in some way based on timestamps of neighboring documents and if non have a timestamp they are all assumed to have happened \"just now\" for simplicity. */
    public var history: [HistoryEntry]?

    public init(history: [HistoryEntry]? = nil) {
        self.history = history
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case history
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(history, forKey: .history)
    }
}

