//
// InputUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Information about a user provided as input for an search  Currently this can either be the users &#x60;id&#x60; oder a users &#x60;history&#x60;.  */
public enum InputUser: Codable, JSONEncodable, Hashable {
    case typeInputUserById(InputUserById)
    case typeInputUserWithHistory(InputUserWithHistory)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeInputUserById(let value):
            try container.encode(value)
        case .typeInputUserWithHistory(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(InputUserById.self) {
            self = .typeInputUserById(value)
        } else if let value = try? container.decode(InputUserWithHistory.self) {
            self = .typeInputUserWithHistory(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of InputUser"))
        }
    }
}

