//
// StatelessPersonalizedDocumentsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StatelessPersonalizedDocumentsResponse: Codable, JSONEncodable, Hashable {

    public var warnings: [String]?
    public var documents: [PersonalizedDocumentData]

    public init(warnings: [String]? = nil, documents: [PersonalizedDocumentData]) {
        self.warnings = warnings
        self.documents = documents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case warnings
        case documents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(warnings, forKey: .warnings)
        try container.encode(documents, forKey: .documents)
    }
}

