//
// UserInteractionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum UserInteractionType: String, Codable, CaseIterable {
    case positive = "Positive"
}
