//
// UserInteractionData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserInteractionData: Codable, JSONEncodable, Hashable {

    /** A document id can be any non-empty UTF-8 string that does not contain the null byte. It may consist of digits, Latin letters, underscores, colons, minus signs, at signs, and dots. */
    public var id: String?
    public var type: UserInteractionType?

    public init(id: String? = nil, type: UserInteractionType? = nil) {
        self.id = id
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

